### ISSUE TITLE
Custom cursors in some games are washed out

### ISSUE THREAD

**Issue by Truuun** [ledoge/novideo_srgb#24]
First of all, thank you for writing this very nice software. It's great to be able to both clamp my wide gamut monitor to srgb and use a color calibration at the same time without having to set up something like a lut in reshade for each game that I play. 

I have noticed something odd happening in some games that use their own mouse cursor: they get very washed out when the clamping is on.
I am able to verify how the cursors should look by using the sRGB mode on my monitor or looking at the content with a screen that does not have a wide gamut.

List of confirmed games:
-World of Warcraft
-Patfhinder: Wrath of the Righteous
-Halo: The Master Chief Collection
-Mass Effect 3: Legendary Edition
-Crysis 3

Some details about my setup:
Monitor: LG27GP950
Graphics card: MSI GeForce GTX 3080 Ti Gaming X Trio 12G
OS: Windows 11

**Comment by ledoge** [comment]
I've heard about this from multiple users now, unfortunately it seems to be an unavoidable side effect caused by the fact that cursors are rendered separately as an overlay in hardware, and that interacts with the color space transform in a bad way. I think if you force software rendering of the cursor, e.g. using [this](https://www.monitortests.com/forum/Thread-SoftCursor), it should look as intended.

**Comment by Truuun** [comment]
Thanks for the quick response! What is mentioned in that post is excactly the issue I encountered. I'll give it a shot, thanks!

**Comment by Truuun** [comment]
That did indeed solve the problem. :)
