### ISSUE TITLE
Editable EDID

### ISSUE THREAD

**Issue by carolp0** [ledoge/novideo_srgb#31]
I would love a version with editable EDID variables.

**Comment by ledoge** [comment]
Probably not going to add this because it seems like too much of an edge case. The way I see it, people who want accurate colors beyond the EDID data will either have their own ICC profile or have downloaded one from somewhere else, and therefore have no need for manual entry of xy coordinates. And if you really do need that, you can generate a synthetic ICC profile using DisplayCAL to get the same effect. Does that work for your use case?
