### ISSUE TITLE
Simple question on usage

### ISSUE THREAD

**Issue by wards999** [ledoge/novideo_srgb#39]
Apologies if I'm missing something but:

- Do I need to keep the program running at all times?
- Do I need to re-launch it at every reboot?

Thanks

**Comment by Tallulah88** [comment]
No and, no. You just run it one time and after that you can close it and you will not need to do it again. Anyways is good to check from time to time, because things like updating Windows, updating the GPU or disconnecting/connection other displays can make it stop working. I have issues sometimes when I change between displays or I connect a new one. But if you don't change anything and there are no big system updates it will work without reopening the program.

**Comment by ledoge** [comment]
With the new release, you can leave it running minimized to have it automatically reapply the clamp on monitor changes, including HDR handling. If you don't toggle HDR and also don't run into any driver bugs that break the clamp somehow, there's no reason to have it running in the background.

**Comment by wards999** [comment]
Thanks, so, essentially the only time to launch again and re-clamp would be :

- after a physical monitor swap
- after a graphics driver update
- after a windows update
- after a HDR toggle change

**Comment by ledoge** [comment]
The README now explicitly mentions this.
